### ISSUE TITLE
Properly handle timezones

### ISSUE THREAD

**Issue by mdbecker** [pennsignals/dsdk#8]
Right now we're using timezone unaware `datetime`s. This causes issues when you try to compare timestamps that come out of a mongo `ObjectId` (via `generation_time`). It might work when comparing against `datetime`s that come out of a mongo document (i.e. fields other than _id that are passed in as a `datetime` to mongo). I'm not even sure what will happen with `datetime`s that come out of mssql.

This task entails implementing a `datetime` timezone strategy that works for at least all of these cases.

**Comment by jlubken** [comment]
There is a parameter for `MongoClient(uri, ... tz_aware=True)` that causes mongo to return non-naive datetimes for datetime doc attributes. Move mongo connectivity from `dsdk.util` to `dsdk.mongo` and make this default.

Check for similar configuration for `pyodbc`, `pymssql`, and preferrably the `freetds` driver.

Postgres has specific naive and non-naive time and datetime column types.

Update the code with naive:
```
from datetime import datetime
...
datetime.utcnow()
```
... to non-naive:
```
from datetime import datetime, timezone
...
datetime.now(timezone.utc)
```

Use `dateutil` instead of `pytz` if more is needed: https://blog.ganssle.io/articles/2018/03/pytz-fastest-footgun.html

**Comment by mdbecker** [comment]
Split this into 2 separate cards:

1. Store datetimes as epoch time in mongo (milestone 1)
   - Utility functions for dsdk users to return the correct epoch time for storage in a db (milestone 1)
2. Stop using generation_time in cdisepsis (milestone 1)
3. Make sure we solve this for front-end apps too (milestone 2)

**Comment by mdbecker** [comment]
Replaced by #36 and a separate cdisepsis task
